### ISSUE TITLE
Mis-alignment issue on column block

### ISSUE THREAD

**Issue by derjones-adobe** [adobe/spark-website#168] opened 2021-06-30 23:52 UTC
**Example page:** https://www.adobe.com/express/feature/image/remove-background

**Screenshot:** 
<img width="1553" alt="image" src="https://user-images.githubusercontent.com/81582751/124044872-425a5b00-d9c3-11eb-9162-f685bef25070.png">

- Expected Behavior: Copy and imagery should align in a column block
- Actual Behaviour: Imagery and copy are not aligned on any page when column block is uses

**Comment by rofe** [comment] 2021-07-01 06:49
This rtegression might have been caused by the fix for https://github.com/adobe/express-website-issues/issues/138 (#163)

Temp fix was to remove the `baseline` instruction.

**Comment by rofe** [comment] 2021-07-01 09:53
I can confirm that the fix for this issue undid the fix for https://github.com/adobe/express-website-issues/issues/138 

@MarquiseRosier I think that one's less prominent but it would be great to find a fix for both use cases. Maybe only align `baseline` for 3 or more columns? Ore only when `centered` is added as an option class?

**Comment by rofe** [comment] 2021-09-29 08:54
I think this can be closed.

**Closed by rofe** 2021-09-29 08:54 UTC
